### ISSUE TITLE
If someone has the shop-formspec open while another buys a pet, this someone can still buy it from the other

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#101]
Repro:

Have three accounts A,B,C

1. A has a camel, B and C have a stick each
2. A sets the camel to be sold for 1 stick
3. B rightclicks the camel, opening the Shop formspec
4. C rightclicks the camel, also opening the Shop formspec
5. B buys the camel for 1 stick
-> A gets the "you sold the camel" message, B gets the "you bought a camel" message
6. C buys the camel for 1 stick
-> B gets the "you sold the camel" message, C gets the "you bought a camel" message
7. Owner of the camel is now C. It should be B, because he bought first. C should not be able to purchase.

Step 5 works for both, whoever clicks first. B and C could switch places after step 5

For my reference 931

**Comment by runsy** [comment]
Fixed in the very last release. Now the seller is checked as the owner.

Thanks for your report.
