### ISSUE TITLE
Beehive does not respect protection

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#102]
Players who cannot dig the hive, can still remove honey from it. I'm not sure whether this is intended behavior or not, but some players have complained.

**Comment by runsy** [comment]
The hive can be digged. Probably you have activated a protector mod.

**Comment by fluxionary** [comment]
> The hive can be digged. Probably you have activated a protector mod.

That's not the problem. We're using the `areas` mod. The problem is that if player A owns the area, and puts down a hive, Player B, who does not own the area or the hive, can steal the honey.

**Comment by runsy** [comment]
Oh, yeah, this is how it works. Behives have not owner. It does not matter wether the area is protected or not.

**Comment by fluxionary** [comment]
I could add an owner in a PR, if that is how you think it should behave. Otherwise, I will probably just write a patch for our own server. Both options are fine by me :)

**Comment by fluxionary** [comment]
@runsy would you rather i submit a PR adding this behavior, or just change it on our local server? or i could even submit a PR that makes it a config option.

**Comment by runsy** [comment]
What patch did you do?

**Comment by runsy** [comment]
New version:
- Added a new setting, 'protect_beehive' to avoid honey plundering. False by default.
- if 'protect_beehive' and the placer is a player, that beehive has that owner.
- Already placed beehives in the game and wild beehives (created by a Queen Bee) have "Unknown" owner and can be plundered.
