### ISSUE TITLE
5.6.0server error

### ISSUE THREAD

**Issue by cosoc** [runsy/petz#105]
AsyncErr: Lua: Runtime error from mod 'petz' in callback luaentity_Activate(): ...test/minetest_client/bin/../builtin/common/serialize.lua:191: bad argument #1 to 'loadstring' (string expected, got nil)
stack traceback:
	[C]: in function 'loadstring'
	...test/minetest_client/bin/../builtin/common/serialize.lua:191: in function 'deserialize'
	...etest_client/bin/../mods/petz/petz/api/api_init_prop.lua:293: in function 'set_initial_properties'
	...netest_client/bin/../mods/petz/petz/petz/pony_mobkit.lua:105: in function <...netest_client/bin/../mods/petz/petz/petz/pony_mobkit.lua:103>

**Comment by appgurueu** [comment]
Possibly related to #11427, but rather looks like a clear petz bug to me: `nil` is passed to `minetest.deserialize`.

**Comment by runsy** [comment]
> > The serialize/deserialize code had changed.
> 
> Yes, obviously? I still see no case to be made for a regression. Granted, I have removed the type check and replaced it with an error, but petz shouldn't be passing `nil` to `minetest.deserialize`. There exist multiple quick solutions:
> 
>     1. `minetest.deserialize(str or "return nil")`: This will deserialize `str=nil` to `nil`
> 
>     2. `local _, val = pcall(minetest.deserialize(str))`: `val` will hold `nil` if `str` is not a string or some other error occurs
> 
>     3. `local val; if str then val = minetest.deserialize(str) end`: `val` will only be set if `str` is non-nil
> 
>     4. `str and minetest.deserialize(str)`: Will be `nil` or `false` if `str` is falsy

The problem is that it is a table not a string.

**Comment by appgurueu** [comment]
> The problem is that it is a table not a string.

Then I'm afraid your code is completely broken (and was broken all along, this PR only didn't silence the bugs any longer). You'll have to debug it.

**Comment by runsy** [comment]
> > The problem is that it is a table not a string.
> 
> Then I'm afraid your code is completely broken (and was broken all along, this PR only didn't silence the bugs any longer). You'll have to debug it. Why don't you just remove the `minetest.deserialize` there? You're trying to deserialize something that was already deserialized.

Yes, the code was bad. Ive solved. Thanks.

**Comment by runsy** [comment]
> > The problem is that it is a table not a string.
> 
> Then I'm afraid your code is completely broken (and was broken all along, this PR only didn't silence the bugs any longer). You'll have to debug it. Why don't you just remove the `minetest.deserialize` there? You're trying to deserialize something that was already deserialized.

Yes, the code was bad. Ive solved. Thanks.

**Comment by runsy** [comment]
> > The problem is that it is a table not a string.
> 
> Then I'm afraid your code is completely broken (and was broken all along, this PR only didn't silence the bugs any longer). You'll have to debug it. Why don't you just remove the `minetest.deserialize` there? You're trying to deserialize something that was already deserialized.

Yes, the code was bad. Ive solved. Thanks.
