### ISSUE TITLE
infinite free silk duplication

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#107]
via a user on the `your-land` server:

```
[Spinning wheel bug] You can create Silk bobbin by putting 3 cocoons to Spinning wheel. But after you place spinning wheel, there is already 1 cocoon inside (hardcoded). So digging/placing spinning wheel each time you craft silk will save you 1 cocoon. 2 cocoons = 1 silk. :P
```

it seems that either it should not come w/ a free silk bobbin when placed, or that it should keep track of the number of bobbins via node/item metadata.

**Comment by runsy** [comment]
But when you craft a spinning_wheel it is necessary a silk_bobbin.

**Comment by fluxionary** [comment]
> But when you craft a spinning_wheel it is necessary a silk_bobbin. Why infinite?

i see, i used the wrong wording. place the spinning wheel. it has 1 cocoon already in it. add 2 cocoons, take the bobbin. break the wheel and place it again. it now has a free cocoon in it again.

**Comment by runsy** [comment]
Fixed in the new version:
- New setting "silk_to_bobbin", this is the amount of silk to craft a bobbin in a Spinning Wheel.
- Before the silk count reset to zero when a bobbin was created, now one silk always remains.

**Comment by fluxionary** [comment]
your fix is semantically identical to just setting it to 0 always when it is placed, but is more confusing. why report that there's e.g. 3 silk in the wheel when it only takes 2 cocoons to craft a bobbin?

**Comment by runsy** [comment]
> your fix is semantically identical to just setting it to 0 always when it is placed, but is more confusing. why report that there's e.g. 3 silk in the wheel when it only takes 2 cocoons to craft a bobbin?

What do you propose

**Comment by fluxionary** [comment]
Sorry I didn't respond, email client hasn't checked for messages in almost a week. 

I think just having it set the silk count to 0 would be fine. I'd also be happy to code a PR so that the # of silk that are in the wheel is stored in item metadata when you break the node.

**Comment by runsy** [comment]
> Sorry I didn't respond, email client hasn't checked for messages in almost a week.
> 
> I think just having it set the silk count to 0 would be fine. I'd also be happy to code a PR so that the # of silk that are in the wheel is stored in item metadata when you break the node.

Done.
