### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by brylie** [runsy/petz#11]
I have tried several times to get this mod to work, but it doesn't seem to load on our server. Could you please provide step-by-step installation instructions?

**Comment by runsy** [comment]
1) Decompress it in the 'mods' folder.

2) Download the mobkit mod and decompress in the mods folder too.
[Download](https://github.com/TheTermos/mobkit/archive/master.zip)

Done!

For extra help please goto the forum thread:
[Forum thread](https://forum.minetest.net/viewtopic.php?f=9&t=22245)

**Comment by brylie** [comment]
Are there any changes needed in the world.mt file?

**Comment by runsy** [comment]
No

**Comment by runsy** [comment]
Did you solved?

**Comment by brylie** [comment]
Well, this seems to conflict somehow with the mobs plug-in, and now we can't get either to work on our server.

**Comment by runsy** [comment]
No, I have both and zero problems.

**Comment by brylie** [comment]
Hm. Not sure why things stopped working on our server then. I will try again soon.
