### ISSUE TITLE
Cow poops floating in air

### ISSUE THREAD

**Issue by mazes-80** [runsy/petz#118]
in api_poop there is already something to put y = y -0.5, but for cows the offset should be higher.
despite poops are falling nodes nothing triggers the fall.
You may do this way but poops should also be buildable_to, else cow will produce stacked poop

**Comment by runsy** [comment]
I will fix it.

**Comment by runsy** [comment]
Now the poop engine check the kitz stand_pos position, that is the accurate position of the surface where the petz stands.
Fixed.
