### ISSUE TITLE
should penguin eggs be hatchable?

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#122]
they don't lay eggs in a nest, but should they lay them on the ground? they don't seem to be breed-able either.

**Comment by runsy** [comment]
penguins can lay eggs, not in the nest but in the ground.

But very rarely, because the eggs stand forever and can oversaturate the landscape.

You can reduce the "lay_egg_timing" setting to eggs to appear more frecuently.

**Comment by fluxionary** [comment]
alright, i should have mentioned i knew the egg items were dropped, i'll report back that they aren't intended to hatch.
