### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by mazes-80** [runsy/petz#13]
Sorry I'm not a huge fan of PR, but here are my two cents:
[petz.tr.fr.txt](https://github.com/runsy/petz/files/4082134/petz.tr.fr.txt)

If you have a few time for me, I'll try to give you feedback via IRC.

**Comment by runsy** [comment]
Thanks! Translations are good for reaching more people.
Yes, just tell me when you log on, I'm 'runs' there.

**Comment by mazes-80** [comment]
Typos fix and improvements (mostly because english doesn't need gender for words)
[petz.tr.fr.patch1.txt](https://github.com/runsy/petz/files/4083004/petz.tr.fr.patch1.txt)

I currently organize my playing experience feedbacks in a note pad.

**Comment by runsy** [comment]
Fixed the translation.
Thanx.
