### ISSUE TITLE
petz sets which are dead can't be placed

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#131]
a player on your-land reports:
```
I have 2 petz:silkworm_set that I can´t place
```

turns out this is because they are dead:
![image](https://user-images.githubusercontent.com/25628292/204691634-dda520c6-5113-4353-9e36-c19325a79ccb.png)

i'm not sure what the "correct" solution to this is, but it is *not* just having the mob disappear when someone tries to place it. there needs to at least be some sort of message.

**Comment by runsy** [comment]
How could get a dead silkworm?

**Comment by runsy** [comment]
Anyway, I have made a fix to avoid to capture or place dead petz.

**Comment by runsy** [comment]
> > How could get a dead silkworm?
> 
> i assume this was a side effect of #119.

The hp for the silkworns was 0?

**Comment by fluxionary** [comment]
> The hp for the silkworns was 0?

that *is* odd, but i don't have any other theories. 

this doesn't seem to be an epidemic though, so far it's just 2 silkworms that had this issue.

**Comment by runsy** [comment]
> > The hp for the silkworns was 0?
> 
> that _is_ odd, but i don't have any other theories.
> 
> this doesn't seem to be an epidemic though, so far it's just 2 silkworms that had this issue.

Well, now when the player try those silkworms to place, a message of warning will appeared and the itemsatck would be removed.

**Comment by fluxionary** [comment]
oh, i was wrong, the HP wasn't 0, just the life timer.

**Comment by runsy** [comment]
> oh, i was wrong, the HP wasn't 0, just the life timer.

OK, I have made a new version that checks if the petz is dead. So:
- A dead petz not removed would be removed in the next server restart.
- Dead petz cannot be captured.
- Already captured petz will be removed when placed.
