### ISSUE TITLE
shop buyer formspec "Unable to load texture"

### ISSUE THREAD

**Issue by blaboing** [runsy/petz#138]
Buyer gets error "GUIFormSpecMenu::parseImage() Unable to load texture" if price is set to dirt/cobblestone

**Comment by runsy** [comment]
To set the price you must put:

`selling_exchange_items = selling_exchange_items = default_dirt,default:cobble`

Try to avoid spaces.

**Comment by blaboing** [comment]
Just checked and there aren´t any spaces in petz.conf or user.conf

`selling_exchange_items = default:stick,default:dirt,default:cobble,default:steel_ingot,default:gold_ingot,default:diamond`

**Comment by runsy** [comment]
> Just checked and there aren´t any spaces in petz.conf or user.conf
> 
> `selling_exchange_items = default:stick,default:dirt,default:cobble,default:steel_ingot,default:gold_ingot,default:diamond`

Fixed.
