### ISSUE TITLE
Bonemeal: gelatin support

### ISSUE THREAD

**Issue by mazes-80** [runsy/petz#14]
Improve bonemeal integration
[petz-bonemeal-compat-improve.patch.txt](https://github.com/runsy/petz/files/4083044/petz-bonemeal-compat-improve.patch.txt)

By the way I use [TenPlus1 bonemeal](https://notabug.org/TenPlus1/bonemeal)
no idea if gelatin is present in other bonemeal mods

**Comment by mazes-80** [comment]
[petz-bonemeal-compat-improve.patch.txt](https://github.com/runsy/petz/files/4083794/petz-bonemeal-compat-improve.patch.txt)
will fork and PR from now on

**Comment by runsy** [comment]
You cannot do "petz:bone 2" in the recipes.
Merged. Thanx.
