### ISSUE TITLE
gecko spawn chance a tiny bit too high

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#142]
This is the relevant part of the user.conf:

```
## Max number of mobs in the active block range
max_mobs = 60

## Chance to spawn a mob if there are no other objects in area
# the value should be 0 - 1
spawn_chance = 0.99

#do not spawn in protected
no_spawn_in_protected = true
```

The gecko spawns not only in protected areas, but also on the screenshot are visible a lot and active entities are 2600. If you want, you may happily visit the testserver and read out any value you need :D 

For my reference: 3546

**Comment by Bastrabun** [comment]
![image](https://user-images.githubusercontent.com/59294479/212872519-8d6941c1-907b-4021-bb8c-7fe82ad55b62.png)

**Comment by runsy** [comment]
Fixed: Added a gecko_max_laid_eggs setting, 1 by default.

**Comment by runsy** [comment]
New fix:

z46

- Fix: Now gecko's eggs hatching respects the max_mobs and the max_per_species settings.
