### ISSUE TITLE
when feeding a petz to heal it, it shows the health before it was healed, not after

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#149]
e.g. if a puppy has 7 health, and i give it some raw meat, i am informed "Puppy at full health (7)", even though it now has 8 health.

**Comment by runsy** [comment]
I think it is OK, not the previous health, but the max health, i.e., no matter how much you feed it, it will not be able to exceed the max health.

**Comment by fluxionary** [comment]
![image](https://user-images.githubusercontent.com/25628292/214978241-c2838c4f-d967-4c1f-881e-ea22de8e4f65.png)

it's not the max health. it shows one value when you heal it to full, and then the a different value when you feed it again.

**Comment by runsy** [comment]
Fixed.
