### ISSUE TITLE
geckos do ... this

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#161]
they're stuck:
https://user-images.githubusercontent.com/25628292/229324324-1bcb0ca5-3be2-47f6-8703-27c4d0da31e5.mp4

EDIT: if that attachment doesn't work, try https://gitea.your-land.de/attachments/f4a13fe7-9778-4543-93f2-25bf055d4fc8

**Comment by runsy** [comment]
Changed gecko collisionbox.
