### ISSUE TITLE
petz.conf: ant laid egg error

### ISSUE THREAD

**Issue by mazes-80** [runsy/petz#163]
In petz.conf you set:

`max_laid_anteggs = 500`

when it should be
`ant_max_laid_eggs = 500`

for now this param is ignored and max_laid_egg for ants is defaulting to 10. I just saw it when reworking my user.conf as I investigated about chicken eggs. Changing it may lead to ant over population, I did not test as I disabled ants in my worlds.

**Comment by runsy** [comment]
No, the ants have a different behaviour, br_ant.lua

**Comment by runsy** [comment]
Yes the squirrel behaviour is erratic whwn a log of wood near them.  I have to improve it.

**Comment by runsy** [comment]
Fixed.
