### ISSUE TITLE
Exploding Population

### ISSUE THREAD

**Issue by acmgit** [runsy/petz#164]
![screenshot_20230407_171551](https://user-images.githubusercontent.com/9446707/230644298-70d51919-14dc-40ef-8a4a-a6279a55e0d6.png)

It seems, petz ignores the settings, the population explodes in few seconds.
Take a look at the Screenshot.

Werewolf only jump up and down without a move into a direction.
Squirrels try always jump on the same place to climb up, but they to small ...

**Comment by runsy** [comment]
Check your spawn_interval setting in petz.conf and user.conf

**Comment by runsy** [comment]
Werewolves' crazy jumping fixed.

**Comment by runsy** [comment]
Yes the squirrel behaviour is erratic whwn a log of wood near them. I have to improve it.

**Comment by acmgit** [comment]
[user.conf.txt](https://github.com/runsy/petz/files/11184524/user.conf.txt)
[petz.conf.txt](https://github.com/runsy/petz/files/11184527/petz.conf.txt)

Both here, i can't find something wrong there, maybe you can help me.
Thanks.

**Comment by runsy** [comment]
Put:
spawn_interval=30
spawn_chance=0.3

**Comment by acmgit** [comment]
Thank you, i will change this values.

**Comment by acmgit** [comment]
[profile-20230410T212537.csv](https://github.com/runsy/petz/files/11194275/profile-20230410T212537.csv)
[profile-20230410T220816.csv](https://github.com/runsy/petz/files/11194276/profile-20230410T220816.csv)

Sorry, for me looks like, that petz ignores the config. When i clear the mobs with /clear_mobs petz:, in the next second is new spawn.
I have checked the werewolf, they should spawn rarly, but there often places, there are 3 Werewolfes at the same time.
Maybe you can take a look at the profiles, and there are very much entries with petz.

**Comment by runsy** [comment]
send me your petz.conf and user.conf please

**Comment by runsy** [comment]
I will redo the spawn engine to geit it more accurate and fast.

I saw I could do a lot of tweaks.

**Comment by acmgit** [comment]
Thank you. The petz.conf is the original petz.conf. The user.conf have i removed.

**Comment by acmgit** [comment]
With your original conf it's better. But petz generates a lot of loads.
