### ISSUE TITLE
It checks only the first area

### ISSUE THREAD

**Issue by acmgit** [runsy/petz#176]
All additonal areas will be ignored.

The problem is at in kitz/engine.lua function function kitz.get_spawn_pos_abr(abr).
Line 261 - 263.
Is the player in the first area, it works well.
Is the player not in the first area, then you jump out of the loop. So all additional areas will be ignored.
```
		for _, _area in ipairs(petz.settings.spawn_areas) do
			local points = string.split(_area, ';')
			local area = {}
			for i = 1, 2 do
				local axis = string.split(points[i])
				if #axis == 3 then
					area[i] = vector.new(tonumber(axis[1]), tonumber(axis[2]), tonumber(axis[3]))
				end
			end
		        if #area == 2 and not(spawn_inside_area(spawn_pos, area)) then
				return false, false
			end
		end
```

**Comment by runsy** [comment]
Fixed.
