### ISSUE TITLE
Gray Paving Stone, Red Gables and Yellow Paving behaves like wood

### ISSUE THREAD

**Issue by Wuzzy2** [runsy/petz#18]
Gray Paving Stone, Red Gables and Yellow Paving behave like wood:

* Flammable
* Wrong groups: wood, flammable, oddly_breakable_by_hand, choppy
* Wood sounds

**Comment by runsy** [comment]
Solved.
Thanx 4 ur review

**Comment by Wuzzy2** [comment]
Unfortunately, the stair+slab variants of red gables are still woodlike.

**Comment by runsy** [comment]
Solved.
