### ISSUE TITLE
Place user.conf in world folder

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#182]
Please allow the user.conf be placed in the world folder, either additionally to the one in the mod itself or exclusively.

To not conflict with other files, please name it `petz_user.conf` or similar.

You could also remove it from .gitignore in case it resides exclusively in the world folder and this would make updating petz a lot easier, not only when working with git.

For my reference 4452

**Comment by fluxionary** [comment]
my personal preference is that the file should be called `petz.conf` instead of `petz_user.conf`, but that is minor.

**Comment by runsy** [comment]
Done.

```
# WARNING: Do NOT change the Petz Mod preferences here
#Do create a 'user.conf' file in the mod dir with your favourite preferences instead of.
#Alternatively you can create a  'petz.conf' file in the world folder.
#Note: Creating a 'petz.conf' in the world folder will disable the 'user.conf' if it exists.
```
