### ISSUE TITLE
some animals still don't die when in lava

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#185]
![image](https://github.com/runsy/petz/assets/25628292/b0895224-9120-4056-874d-765e9f685fc3)

the full list of survivors:

beaver, bunny, chicken, chimp, clownfish, dolphin, ducky, male elephant, frog, gecko, goat, hamster, hen, kitty, lamb, lion, panda, penguin, piggy, puppy, rooster, silkworm, squirrel, tropical fish, turtle

**Comment by runsy** [comment]
Fixed.
