### ISSUE TITLE
polar bear texture issue

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#189]
the inside of the polar bear's front left leg is partially transparent and has the toes/claws on the top:

![image](https://github.com/runsy/petz/assets/25628292/5788497c-d73d-4e9c-aedc-fd55612bb0fb)

**Comment by Sunrader** [comment]
I fixed this, remapped the UV map for the polar bear leg to fit and be right side up.
[https://dee.email/OPEN/Minetest/MTPics/PETZ/remapped_petz_polar_bear.b3d](url)
Just rename to petz_polar_bear.b3d and replace the old one in /models
Sorry, still haven't figured out git well enough to put files here!

**Comment by runsy** [comment]
Thank you!
