### ISSUE TITLE
Beaver Dam Branches in wood group

### ISSUE THREAD

**Issue by Wuzzy2** [runsy/petz#19]
Beaver Dam Branches are in the wood group. This leads to the odd result that they can be used in many crafting recipes, like for crafting chests. I recommend to remove the wood group from this node.

Same for:

* jackolantern grenade

**Comment by runsy** [comment]
Solved:
- Beaver Dam Branches now in the 'leaves' group.
- Removed wood group for jackolantern grenade.

**Comment by Wuzzy2** [comment]
Why `leaves`? That doesn't sound right either …

**Comment by runsy** [comment]
> Why `leaves`? That doesn't sound right either …

Beaver branches are formed by wood and leaves, it is the same case of vines.

So what group do you suggest? or no group?

**Comment by Wuzzy2** [comment]
Note that `leaves` is used by some mods as a crafting group. That's why I was concerned. It's rarely a good idea to abuse existing groups beyond their intended scope.

You could introduce a new group if beavers need to know that. But I don't know the inner workings well, you decide.

**Comment by runsy** [comment]
No necessary, is a decorative block.
I decided to remove.
