### ISSUE TITLE
Whistle only works when tamagotchi is off?

### ISSUE THREAD

**Issue by Sunrader** [runsy/petz#191]
It seems this is true in my tests. Why would it do that?
Is it intentional?

**Comment by runsy** [comment]
No, it does not depends on tamagochi mode.

**Comment by runsy** [comment]
Checking the code I get that was a little mess so I have refactored the code.

Check it.

**Comment by Sunrader** [comment]
I tried the new whistle update but, in a new world with just the update and minimal mods, after taming and naming a puppy, I got no list at all.

**Comment by runsy** [comment]
> I tried the new whistle update but, in a new world with just the update and minimal mods, after taming and naming a puppy, I got no list at all.

Fixed.
