### ISSUE TITLE
Whistle  - Tamed Unnamed Random Petz Teleporting

### ISSUE THREAD

**Issue by Sunrader** [runsy/petz#194]
I have tested the newest whistle update, dated 8/7. The list appears correct, but there is some way that unnamed tamed petz are getting mixed in with the named ones and teleporting in their place. I think it may have something to do with pulling petz from inventory where they are already tamed when first created, but I haven't been able to isolate it. This is pic of what I have happening. https://dee.email/OPEN/Minetest/MTPics/PETZ/tamedfish.png The fish was teleported to me instead of the puppy.

**Comment by runsy** [comment]
Fixed.

**Comment by Sunrader** [comment]
This one looks good. Even works on my older play world with a mess of petz all over it. Fingers crossed this is it.
