### ISSUE TITLE
wagons should retain their placement and rotation when the pony is detached

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#198]
a player writes: So far it's impossible to rotate a waggon, once I pick the pony up, the waggon will go back to it's original rotation.

i also noticed that the wagon's collision/selection box is present in a fixed location to the south of the pony no matter the orientation, and this is where the wagon goes if you pick up the pony.

**Comment by runsy** [comment]
Fixed.

Now the selectionbox rotates and keeps its rotation when detached.
