### ISSUE TITLE
Petz mod crash due to tamagochi

### ISSUE THREAD

**Issue by cockerspaniel** [runsy/petz#21]
Hi

We get this error message on crash quite often on our server:

> AsyncErr: environment_Step: Runtime error from mod 'petz' in callback environment_Step(): ...-5.1.1-win64\bin\..\mods\petz\petz/api/api_tamagochi.lua:112: attempt to call field 'remove_owner' (a nil value)

Issue I think disappears when we disable tamagochi, but then we can't get them pregnant. Is it trying to update and remove an owner from a pet and crashing because the owner isn't online at that moment, and if so how can we solve it? If it isn't that what is it? cheers and thanks for the mod

**Comment by runsy** [comment]
No, I changed petz.remove_owner to mokapi.remove_owner.
Fixed in the last version.
:-)
