### ISSUE TITLE
Add compatibility with mineclone 2

### ISSUE THREAD

**Issue by wuniversales** [runsy/petz#24]
https://forum.minetest.net/viewtopic.php?f=47&t=20935

**Comment by runsy** [comment]
It is not compatible right now?

**Comment by wuniversales** [comment]
In the creative mode you can not generate a animals.
Nor can any object be crafted.
I don't know if I'm doing something wrong, the mod is enabled but it doesn't do anything.

**Comment by runsy** [comment]
I've checked. No sorry I do not make it compatible for that specific game. It is a lot of work for a single game.

And mainly because is a Minecraft Clone, a copy of Minecraft, so it has no sense Petz or another mod not already included.
