### ISSUE TITLE
automatic_rotate requires numeric rather than boolean

### ISSUE THREAD

**Issue by Kevin-Sangeelee** [runsy/petz#38]
https://github.com/runsy/petz/blob/77f5c2bdefdfaca555ddea5f2f55567160ed5112/petz/misc/parchment.lua#L55

On minetest 5.3-dev, I've noticed that mods that register entities with automatic_rotate set to a boolean crash my server (ServerError: AsyncErr: ServerThread::run Lua: Invalid field "automatic_rotate" (expected number got boolean).

The doc lua_api.txt now states that this should be zero to disable https://github.com/minetest/minetest/blob/a2199bf62232707e96ece031a00b320d30e34445/doc/lua_api.txt#L6603

Therefore, I think the initialisation should be 'automatic_rotate = 0' to meet the API spec. Note I have not experienced any crashes from petz regarding this (I don't know how to use parchment) - I am simply pointing out an anomaly.

**Comment by runsy** [comment]
Fixed. Thanx.
