### ISSUE TITLE
Texture issue with lycanthrophy

### ISSUE THREAD

**Issue by WulftheNordicRanger** [runsy/petz#42]
The texture for the player gets messed up when in werewolf form 
![screenshot_20200805_032944](https://user-images.githubusercontent.com/34429605/89384383-055ee900-d6cc-11ea-913c-7c3ffbd64642.png)

**Comment by runsy** [comment]
That's armor over the wolf's fur.

**Comment by WulftheNordicRanger** [comment]
That fixed it (it was a front view btw). Didn't realize that someone else made a fork of 3d armor

**Comment by WulftheNordicRanger** [comment]
Spoke too soon, the upgrade didn't fix it

**Comment by runsy** [comment]
> 
> 
> Spoke too soon, the upgrade didn't fix it
> Edit: Also, it seems to be triggered by switching wielded items

what mods do you use?

**Comment by WulftheNordicRanger** [comment]
These are the mods I use
![screenshot_20200817_193842](https://user-images.githubusercontent.com/34429605/90454608-bf3d5880-e0c1-11ea-9909-a88147ea16d7.png)

and it also happens with admin armor

**Comment by WulftheNordicRanger** [comment]
Ok, I tested it and the conflict seems to be with skindb

**Comment by WulftheNordicRanger** [comment]
Since a skin mod of some sort is on almost every server, a way to save the last skin used before transforming and then reapply it afterwards would be a good idea

**Comment by runsy** [comment]
> 
> 
> Since a skin mod of some sort is on almost every server, a way to save the last skin used before transforming and then reapply it afterwards would be a good idea

I am in my holiday time. When I come back I solve it, I hope so.

**Comment by Bastrabun** [comment]
If a solution is too far fetched, is there a way to disable switiching to another model and maybe add a couple of 64x64 werewolf skins instead?
