### ISSUE TITLE
Cow milking: bucket count not decremented when no room in inventory

### ISSUE THREAD

**Issue by mazes-80** [runsy/petz#49]
See [petz-milk_cows.patch](https://github.com/runsy/petz/files/5262780/petz-milk_cows.txt)

It decrement buckets count when milking even when no more room in inventory.
It also allows to keep the bucket stack as wielded item when milking cows, same behavior as when filling buckets with water.

**Comment by runsy** [comment]
I have to check it.

Thanx.

**Comment by runsy** [comment]
Merged.
