### ISSUE TITLE
What does it MEAN??

### ISSUE THREAD

**Issue by crogonint** [runsy/petz#50]
It's broketed:

AsyncErr: ServerThread::run Lua: Runtime error from mod 'petz' in callback luaentity_Step(): ...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:1472: attempt to index local 'node3' (a nil value)
stack traceback:
	...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:1472: in function 'is_in_deep'
	...-5.3.0-win64\bin\..\mods\petz\petz/mobkit/br_aquatic.lua:58: in function 'logic'
	...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:940: in function 'stepfunc'
	....3.0-win64\bin\..\mods\petz\petz/petz/dolphin_mobkit.lua:81: in function <....3.0-win64\bin\..\mods\petz\petz/petz/dolphin_mobkit.lua:80>

It said this while I was chopping leaves and looking for seeds in a forest, about 15 minutes in to game play. Crashed the game, actually.

NO wonder, that's what you get for trying to put a pet dolphin in the middle of an Aspen grove! :P

What do I need to do??

**Comment by crogonint** [comment]
...Two minutes later, trying to chop down the ame Aspen tree:

AsyncErr: ServerThread::run Lua: Runtime error from mod 'petz' in callback luaentity_Step(): ...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:1472: attempt to index local 'node3' (a nil value)
stack traceback:
	...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:1472: in function 'is_in_deep'
	...-5.3.0-win64\bin\..\mods\petz\petz/mobkit/br_aquatic.lua:58: in function 'logic'
	...s\Games\minetest-5.3.0-win64\bin\..\mods\mobkit\init.lua:940: in function 'stepfunc'
	....3.0-win64\bin\..\mods\petz\petz/petz/dolphin_mobkit.lua:81: in function <....3.0-win64\bin\..\mods\petz\petz/petz/dolphin_mobkit.lua:80>

**Comment by crogonint** [comment]
..culling leaves, technically.

**Comment by runsy** [comment]
You are using a old mobkit. The node3 crash was solved in the past.

https://github.com/TheTermos/mobkit/archive/master.zip

**Comment by crogonint** [comment]
? I downloaded the one in the GUI??

Isn't that the newest one?

**Comment by crogonint** [comment]
FYI, that init.lua is identical to the one currently listed on github. I did a compare in Notepad++ to try to sort which is the newest.

Sorry to bother you, it didn't occur to me that the one liste in the GUI wouldn't be current. :/
