### ISSUE TITLE
Placing petz:kennel overwrites nodes in the way regardless

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#52]
When a normal player (without areas privs or anything) places the petz:kennel on the edge of a protection he does not own, they can overwrite whatever is in the way.

Even owned blocks like locked chests and their content is gone.

Please make the kennel optional and make it respect protections.

**Comment by runsy** [comment]
Fixed:
- Kennel placement search for an area of protected nodes.
- You can disable the kennel placement with a new setting: "disable_kennel"
