### ISSUE TITLE
Despite lycanthropy disabled, "unknown" petz:werewolf entites are spawned

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#54]
I disabled lycanthropy in the user.conf

`lycanthropy = false`

but I didn't change the petz_list.

But looks like there are still werewolves spawned. Players discovered unknown entities floating around and the log also says:

```
2020-12-07 12:24:19: ERROR[Server]: LuaEntity name "petz:werewolf" not defined
2
```

Is that a bug or do I need to also change the petz_list?

For my reference: #109

**Comment by runsy** [comment]
You had this setting to true before? If yes you have to clear old spawned entities.

lycantrhopy = false means werewolves not spawn but ALSO literally the file where the entity is defined not loaded (no models/not textures).

It better put lycantrhpy = true and werewolf not spawn.
