### ISSUE TITLE
Can't ride pony or acess its menu

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#55]
This affects only the pony. Camels seem to work properly.

When I rightclick a pony emptyhanded, it shows heart icons, next time I click it says "pony is already rut"

I can neither ride nor access the menu of the pony, regardless of shift+click, shift+rightclick or any other attempt.

For my reference: #109

**Comment by runsy** [comment]
Yes, caused by a regression when I refactored the settings code.

Fixed.
