### ISSUE TITLE
Feature Request: More Pony Coat Colors

### ISSUE THREAD

**Issue by WulftheNordicRanger** [runsy/petz#61]
For whatever reason, sometime last year I made some textures for some coat patterns seen in various breeds of horse. I wanted to share them in case you wanted to include some more coat options. 

![petz_pony_tan_dun](https://user-images.githubusercontent.com/34429605/105139442-3aca8800-5aee-11eb-87e8-bde3eecddf7a.png)
![petz_pony_palminino](https://user-images.githubusercontent.com/34429605/105139471-46b64a00-5aee-11eb-9160-83d153d3ab4d.png)
![petz_pony_gold](https://user-images.githubusercontent.com/34429605/105139483-4ae26780-5aee-11eb-88ed-af8b2d6bb38c.png)

Feel free to do what you wish with them, I am releasing them as public domain

**Comment by runsy** [comment]
I will add the brown one. I like it. The yellow ones are too much lemonade yellow for my taste :-D

**Comment by runsy** [comment]
Merged.
