### ISSUE TITLE
Milk male cows ... ?

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#62]
After the latest update I can milk male cows. I assume that's not intended :D

For my reference: #218

**Comment by runsy** [comment]
No, i will solve.

**Comment by runsy** [comment]
Fixed in code.

**Comment by DarwinSurvivor** [comment]
Um, actually your fix made *only* males milkable.

`	if not self.is_male then
		minetest.chat_send_player(clicker:get_player_name(), S("Milk only female animals!"))
		return
`

The above causes non-males (ie: females) to return the message and quit the function, therefore only males can be milked.
