### ISSUE TITLE
suggestion: protect petz

### ISSUE THREAD

**Issue by NathanielFreeman** [runsy/petz#65]
I love my adorable petz and I do not want them to be killed on servers, I would like to suggest that (domesticated) petz cannot be killed within [protected areas](https://content.minetest.net/packages/ShadowNinja/areas/), or maybe only the owner of the petz can hurt them. Or some configuration factor to make domesticated petz invulnerable :)

Amo mis adorables mascotas y no quiero que las maten en servidores, me gustaria sugerir que las mascotas (domesticadas) no se puedan matar [dentro de areas protegidas](https://content.minetest.net/packages/ShadowNinja/areas/), o tal vez que solo el dueño de la mascota la pueda herir. O algun factor de configuracion para hacer las mascotas domesticadas invulnerables :)

**Comment by runsy** [comment]
You can now put Dreamctachers to protect them.
