### ISSUE TITLE
Hunger_ng support - some foods ar missing

### ISSUE THREAD

**Issue by daretmavi** [runsy/petz#66]
Hi,

for some foods are satiates levels not defined.
Like
`petz:beef, petz:chicken_legs, petz:raw_porkchop, petz:raw_parrot, petz:raw_goat, petz:raw_ducky, petz:raw_chicken, petz:mini_lamb_chop, petz:honey_bottle, petz:frog_leg, petz:raw_rabbit, petz:roasted_goat_meat, petz:roasted_rabbit, petz:roasted_ducky`
(if I looked correctly)

**Comment by runsy** [comment]
I will check :-)

**Comment by runsy** [comment]
Done :-)
