### ISSUE TITLE
Hard to maintain in a collection of mods

### ISSUE THREAD

**Issue by PeterNerlich** [runsy/petz#68]
*I don't intend to whine around, but I guess I'm very much risking coming across that way. I know that making something like this in ones spare time is very labour intensive and amazing in itself. This is only intended as suggestions in case you do feel comfortable with it and think "Hey, that would be cool to do".*

As someone who runs a minetest server and tries to keep the mods reasonably up to date without major bugs or endless individual feature testing, this mod is a very tedious addition to the list.
Whenever I go through to check out what happened in the mean time and whether I have to pay attention to something, I only see a wall of *commits having mostly similar messages* (e.g. just `fixes`) which make it very hard to get an impression of what exactly changed. Because the commits are usually so many, it is also difficult to have a look at the changes in the code and try to guess for myself what problems may arise, as this mod offers such an impressive number of different animals with different behaviour.

If you say you have the extra time and want to do something like this, trying to write a bit more verbose commit messages would be very helpful. That could be `make frogs hunt ants` instead of `frogs improved` or `simplify conditionals (== true not needed)` instead of `fixes` or something along the lines. From a server maintainer perspective, this helps a lot as it enables the distinction between changes that are probably just mod internal and changes that affect stuff outside of the mod itself, as those minetest 5.4.x `use_texture_alpha` adjustments.

The other thing I could imagine would be to make releases or just version tags wherever you're not in the middle of a bunch of related commits and have a changelog somewhere indicating whether there was anything notable between those versions. I almost guess that this requires even more work though.

*Here I go, this is already another essay where I tell people what to do :see_no_evil: Please don't take it that way, I'm just voicing my ideas. I hope you and all contributors are well, especially through—but not limited to—this pandemic.* :hugs:

**Comment by runsy** [comment]
You are right my commits are chaotic.

I will fix this.

**Comment by PeterNerlich** [comment]
Hey I wanted to dig this up again to say thank you! Your commit messages are very helpful in conveying what changes to expect. Thanks for your work!
