### ISSUE TITLE
mobkit namespace pollution

### ISSUE THREAD

**Issue by NathanSalapat** [runsy/petz#83]
in ptez/petz/misc/behaviours.lua you create a few functions under the mobkit namespace, this can/will cause conflicts if mobkit ever adds functions with the same names. You should be using the petz namespace for any functions you are creating.

**Comment by runsy** [comment]
> in ptez/petz/misc/behaviours.lua you create a few functions under the mobkit namespace, this can/will cause conflicts if mobkit ever adds functions with the same names. You should be using the petz namespace for any functions you are creating.

Yes in the past. But I changed it long time ago. There is not a behaviour.lua indeed. You maybe are using an old version.

You are confused with some mobkit.x functions that does exist in the main mod.

**Comment by NathanSalapat** [comment]
![pollution](https://user-images.githubusercontent.com/8930456/133784828-0b141574-b392-4dc0-a0ae-de5de68d8a26.png)

Grep finds all these...

**Comment by runsy** [comment]
> ![pollution](https://user-images.githubusercontent.com/8930456/133784828-0b141574-b392-4dc0-a0ae-de5de68d8a26.png)
> 
> Grep finds all these...

Yes, but it is a very old version.

Look at:
https://github.com/runsy/petz/tree/master/petz/misc
There is not a behaviours.lua file.

**Comment by NathanSalapat** [comment]
Odd, I'll have to clone a fresh copy, maybe something is messed up with my copy.

**Comment by NathanSalapat** [comment]
Okay, no idea what was going on there. Git said it was up to date, but I did a fresh clone and now all is well. Sorry for wasting your time.
