### ISSUE TITLE
Breeding

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#85]
- A user can grab the seed from any male pony owned by someone else. 

- Sometimes the pregnancy timer is stuck.

For my reference #951

**Comment by Bastrabun** [comment]
It seems to happen to some if not all types. Players reported an elephant and a pony having those problems.

**Comment by runsy** [comment]
It is very difficult to track it.

Maybe a baby is not born cos minetest.add_entity returns nil? In a protected area?

Well, I added a check to it. So in this case there will be an "abortion".

Please, check the last version and report to me if now any abortions ocurred and how.

**Comment by runsy** [comment]
I temporaly close this issue cos no new mention.
