### ISSUE TITLE
cant take egg if player wields hand or stack of the same egg

### ISSUE THREAD

**Issue by blaboing** [runsy/petz#86]
[petz.extract_egg_from_nest](https://github.com/runsy/petz/blob/db3fa98361d366c814ad1b0e9d1502cdc54b065f/petz/api/api_eggs.lua#L41) doesn´t add egg to inventory if player wields hand or stack of the same egg.

Based on this [issue](https://github.com/minetest/minetest/issues/1640) it´s expected behaviour that just needs to be handeld differently.

**Comment by runsy** [comment]
yeah I have to fix it.

**Comment by runsy** [comment]
Fixed.
