### ISSUE TITLE
If someone buys the pony you ride on, you cannot dismount

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#88]
Repro:

1. Set your horse to sell. 
2. Ride on it. 
3. Someone else buys it. 

> Now you can't dismount in a normal way. 

Logging out and back in detaches you ofc, and is the only way to get out, teleport doesn't properly work.

Most likely applies to all ride-ables.

Sometimes I wonder how player come to "test" such stuff :D

For my reference #438

**Comment by runsy** [comment]
Fixed: Now the player arte forced to dismount when his pezt is bought.
