### ISSUE TITLE
Spider taming

### ISSUE THREAD

**Issue by fluxionary** [runsy/petz#97]
Currently:

1. Tarantulas can be tamed.
2. Tarantulas are tamed w/ `"farming:string"`.
3. Tamed tarantulas cannot be picked up w/ a lasso, a net, or a bare hand. 

After learning about this from some confused players, which if any of these are intended behaviors, and which should be changed?

**Comment by runsy** [comment]
- Fixed: Tarantula now can be captured with a net.
